apiVersion: v1
kind: Namespace
metadata:
  name: "{{ REDIS_NAMESPACE }}"
  labels:
    name: {{ REDIS_NAMESPACE }}

---

apiVersion: v1
kind: Namespace
metadata:
  name: "{{ INGRESS_NAMESPACE }}"
  labels:
    name: {{ INGRESS_NAMESPACE }}
