apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ APP_NAME }}
  namespace: "{{ REDIS_NAMESPACE }}"
spec:
  selector:
    matchLabels:
      app: {{ APP_NAME }}
  serviceName: {{ SERVICE_NAME }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ APP_NAME }}
    spec:
      containers:
        - name: redis
          image: redis:5.0-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "{{ REDIS_PASSWORD }}"]
          ports:
            - containerPort: {{ SERVICE_PORT }}
              name: {{ APP_NAME }}
